### PR TITLE
Solved bug on Vue3 reactivity

### PR DESCRIPTION
**Pull request by jbmolle**
With this pull request, the reactivity in the Vue3 example template works.
Also Vue3 recommends using provide/inject instead of app.config.globalProperties so I add it in the pullRequest.
Then we can simply create a function:
```
export const useKeycloak = () => {
  const injection = inject<VueKeycloakInstance>(VueKeycloak.KeycloakSymbol)                                                                                                  
  if (!injection) throw new Error("No keycloak instance provided")                                                                                          
  return injection                                                                                                                                          
}  
```
in a component setup() function to access our keycloak instance.

### CODE REVIEW

**Comment by baltom** [comment]
Tested this with both vue2 and vue3 example.

Vue 2 example `simple_vue2` still works as intended
vue2

However the `typescript_vue3` example just acts as before
vue3

As in, you will get the initial variant of the keycloak object. But it does not update. If you create like a `setInterval` you will see that the object `this.$keycloak` has changed its values. But the view/template itself is static. 

Im aware that vue 3 recommends using provide/inject, however to be compatible with how vue 2 works we are using config.globalConfiguration. But it may be that we simply cannot do that and at the same time support both vue 2 and vue 3

**Comment by jbmolle** [comment]
Hi,
I've added an example with Vite.
If I use the typescript vue3 example, I don't see the update of the token.
But when I compile a Vite example, everything works.

**Comment by jbmolle** [comment]
Hi @baltom 
Could you try the update and the Vite example?
On my side I updated the docker-compose keycloak version to 15 (as the keycloak-js is version 15) and it works fine with the sso iframe.
Could you merge the request and deploy a new beta version so that people can try it and give their feedbacks, please?

**Comment by baltom** [comment]
Yeah, everything except the vue 3 typescript example seems to work fine.

**Review by baltom — APPROVED** [review]

**Pull request merged**
