### PR TITLE
Add typescript definitions

### LINKED ISSUE #23: TypeScript support
Hi,

Are you planning to add TypeScript support in the future?

Thanks!

### PR DESCRIPTION
**Pull request by razbakov**
Closes #23

### CODE REVIEW

**Comment by anderius** [comment]
@razbakov: Thank you very much for your contribution! We will get back to you as soon as we can, and hopefully get this merged and released in a few days!

**Comment by christophernruud** [comment]
Hi and thanks for the PR! Appreciate it. Looks like the config object is using the aliased variables for version 1, so we'll keep it to this versioning scheme at least. These will be deprecated in the next major.

**Comment by anderius** [comment]
We should probably have a look at this file, and maybe be as close to it as possible:

https://github.com/keycloak/keycloak/blob/master/adapters/oidc/js/src/main/resources/keycloak.d.ts

**Comment by wolfuser99** [comment]
This seems to temporary works for me:

1. create vue project with typescript
2. add a file as `shims-keycloak.d.ts` with the next content:
```` typescript
declare module "@dsb-norge/vue-keycloak-js" {
  import Vue, { PluginObject, PluginFunction } from "vue";

  export class VueKeyCloakInstance {
    ready: boolean; // Flag indicating whether Keycloak has initialized and is ready
    authenticated: boolean;
    userName: string; // Username from Keycloak. Collected from tokenParsed['preferred_username']
    fullName: string; // Full name from Keycloak. Collected from tokenParsed['name']
    login: Function; // [Keycloak] login function
    loginFn: Function; // Alias for login
    logoutFn: Function; // Keycloak logout function
    createLoginUrl: Function; // Keycloak createLoginUrl function
    createLogoutUrl: Function; // Keycloak createLogoutUrl function
    createRegisterUrl: Function; // Keycloak createRegisterUrl function
    register: Function; // Keycloak register function
    accountManagement: Function; // Keycloak accountManagement function
    createAccountUrl: Function; // Keycloak createAccountUrl function
    loadUserProfile: Function; // Keycloak loadUserProfile function
    loadUserInfo: Function; // Keycloak loadUserInfo function
    subject: string; // The user id
    idToken: string; // The base64 encoded ID token.
    idTokenParsed: object; // The parsed id token as a JavaScript object.
    realmAccess: object; // The realm roles associated with the token.
    resourceAccess: object; // The resource roles associated with the token.
    refreshToken: string; // The base64 encoded refresh token that can be used to retrieve a new token.
    refreshTokenParsed: object; // The parsed refresh token as a JavaScript object.
    timeSkew: number; // The estimated time difference between the browser time and the Keycloak server in seconds. This value is just an estimation, but is accurate enough when determining if a token is expired or not.
    responseMode: string; // Response mode passed in init (default value is fragment).
    responseType: string; // Response type sent to Keycloak with login requests. This is determined based on the flow value used during initialization, but can be overridden by setting this value.
    hasRealmRole: Function; // Keycloak hasRealmRole function
    hasResourceRole: Function; // Keycloak hasResourceRole function
    token: string; // The base64 encoded token that can be sent in the Authorization header in requests to services
    tokenParsed: string; // The parsed token as a JavaScript object
  }

  export type VueKeyCloakOptions = {
    config?: {
      authUrl?: string;
      authRealm?: string;
      authClientId?: string;
      logoutRedirectUri?: string;
    };
    init?: {
      onLoad: string;
    };
    onReady(keycloak: VueKeyCloakInstance): void;
  };

  declare module "vue/types/vue" {
    // Declare augmentation for Vue
    interface Vue {
      $keycloak: VueKeyCloakInstance;
    }
  }

  export default class VueKeyCloak implements PluginObject<VueKeyCloakOptions> {
    [key: string]: any;
    install: PluginFunction<VueKeyCloakOptions>;
    static install(
      pVue: typeof Vue,
      options?: VueKeyCloakOptions | undefined
    ): void;

    constructor(options: VueKeyCloakOptions);
  }
}

````

**Review by wchaws — APPROVED** [review]

**Comment by wchaws** [comment]
@anderius Any update?

**Comment by anderius** [comment]
No, the problem being that we don't yet use Typescript internally.

We are happy to accept a contribution, but my comment above still stands.

**Comment by baltom** [comment]
Closing this as the will be added with https://github.com/dsb-norge/vue-keycloak-js/pull/68 / https://github.com/dsb-norge/vue-keycloak-js/pull/73

**Pull request closed without merging**
